#create a customer
bob = Customer.create(email: "bob@gmail.com")
sue = Customer.create(email: "sue@gmail.com")
chris = Customer.create(email: "chris@gmail.com")
robert = Customer.create(email: "robert@gmail.com")
david = Customer.create(email: "david@gmail.com")
emily = Customer.create(email: "emily@gmail.com")
ross = Customer.create(email: "ross@gmail.com")
rachael = Customer.create(email: "rachael@gmail.com")


#create a dish
spaghetti = Dish.create(name: "Spaghetti", vegetarian: true, spiciness: 1, calories: 900, price: 12)
hamburger = Dish.create(name: "Hamburger", vegetarian: false, spiciness: 1, calories: 800, price: 20)
cheeseburger = Dish.create(name: "Cheeseburger", vegetarian: false, spiciness: 2, calories: 900, price: 22)
pizza = Dish.create(name: "Pizza", vegetarian: false, spiciness: 1, calories: 1100, price: 15)
baguette = Dish.create(name: "Baguette", vegetarian: true, spiciness: 1, calories: 900, price: 3)
drunken_noodle = Dish.create(name: "Drunken Noodle", vegetarian: false, spiciness: 10, calories: 1000, price: 12)
pad_thai = Dish.create(name: "Pad Thai", vegetarian: true, spiciness: 5, calories: 900, price: 11)
ramen = Dish.create(name: "Ramen", vegetarian: false, spiciness: 8, calories: 900, price: 35)
fettucine = Dish.create(name: "Fettucine", vegetarian: false, spiciness: 1, calories: 1100, price: 15)
steak = Dish.create(name: "Steak", vegetarian: false, spiciness: 3, calories: 1200, price: 20)
pork_chop = Dish.create(name: "Pork Chop", vegetarian: false, spiciness: 2, calories: 1000, price: 18)
filet_mignon = Dish.create(name: "Filet Mignon", vegetarian: false, spiciness: 1, calories: 1300, price: 25)
shrimp_scampi = Dish.create(name: "Shrimp Scampi", vegetarian: true, spiciness: 3, calories: 1100, price: 23)
turkey_burger = Dish.create(name: "Turkey Burger", vegetarian: false, spiciness: 1, calories: 600, price: 20)
caesar_salad = Dish.create(name: "Caesar Salad", vegetarian: true, spiciness: 1, calories: 500, price: 14)
house_salad = Dish.create(name: "House Salad", vegetarian: true, spiciness: 1, calories: 350, price: 12)
seared_tuna_tataki_salad = Dish.create(name: "Seared Tuna Tataki Salad", vegetarian: true, spiciness: 1, calories: 500, price: 20)
cajun_jambalaya_pasta = Dish.create(name: "Cajun Jambalaya Pasta", vegetarian: false, spiciness: 6, calories: 950, price: 18)
